FUSESOC_GET = fusesoc --cores-root . run --setup --build-root build --target sim --tool verilator

ORGANIZATION = roboticowl
PROJECT_NAME = sv-templates

.SILENT:

help:
	@echo "----------------------------------------------------------------"
	@echo "Administrative Targets:"
	@echo "  clean          - removes all temporary files"
	@echo "  clean_libs     - removes the downloaded fusesoc libraries"
	@echo "  clean_build    - deletes the build"
	@echo "  clean_rlt      - deletes the simulation results"
	@echo "  help           - shows this menu"
	@echo
	@echo "FuseSoC Setup Targets"
	@echo "  setup          - install additional libraries"
	@echo "  update         - updates existing libraries"
	@echo
	@echo "Simulation Targets:"
	@echo "  vsim_%          - verilates and simulates the "
	@echo "                   \"${ORGANIZATION}:${PROJECT_NAME}:%\" design"
	@echo "  get_%           - gathers the files for the "
	@echo "                   \"${ORGANIZATION}:${PROJECT_NAME}:%\" design"
	@echo
	@echo "FIle Creation Targets:"
	@echo "  module_%       - creates the source, testbench, and .core files for"
	@echo "                   the \"${ORGANIZATION}:${PROJECT_NAME}:%\" design"
	@echo "                   NOTE: the sub directory is specified by writing "
	@echo "                   make module_% SUB_DIR=directory, and \"directory\""
	@echo "                   MUST already exist"
	@echo
	@echo "Analysis Targets"
	@echo "  svcoverage     - analyzes the coverage data generated by"
	@echo "                   verilator and outputs it to the sv_coverage"
	@echo "                   directory"
	@echo
	@echo "Helper Program Targets:"
	@echo
	@echo "Test Data Generation Targets:"
	@echo
	@echo "----------------------------------------------------------------"


# TARGET OVERRIDES





# GENERIC FUSESOC TARGETS

get_%: clean
	$(FUSESOC_GET) ${ORGANIZATION}:${PROJECT_NAME}:$*

vsim_%: get_%
	bash .scripts/run_verilator.sh



# FILE CREATION TARGETS

export ORGANIZATION
export PROJECT_NAME
SUB_DIR ?= .
module_%: $(SUB_DIR)
	@echo "Creating files for module $* in ${SUB_DIR} ..."
	export SUB_DIR;\
	mkdir ${SUB_DIR}/source &> /dev/null | true;\
	mkdir ${SUB_DIR}/testbench &> /dev/null | true;\
	bash .scripts/mod.sh $* > ${SUB_DIR}/source/$*.sv;\
	bash .scripts/tb.sh $* > ${SUB_DIR}/testbench/tb_$*.sv;\
	bash .scripts/core.sh ${ORGANIZATION} ${PROJECT_NAME} $* > ${SUB_DIR}/$*.core;
	@echo "Done"

# COVERAGE TARGETS

svcoverage:
	verilator_coverage build/logs/* --annotate sv_coverage



# HELPER PROGRAM COMPILATION TARGETS





# TEST DATA GENERATION TARGETS





# FUSESOC SETUP TARGETS

# fusesoc library setup commands look like this: fusesoc library add fusesoc_cores git@github.com:fusesoc/fusesoc-cores
# make sure to use the ssh method rather than the https method when loading from non-public git repos
setup:


reload:
	fusesoc library update



# CLEAN TARGETS

clean: clean_build
veryclean: clean_build clean_libs clean_rlt

clean_libs:
	rm -rf fusesoc_libraries
	rm -f fusesoc.conf

clean_build:
	rm -rf build

clean_rlt:
	rm -rf sv_coverage
	rm -f waveform.vcd*
