FUSESOC_BUILD_SIM = fusesoc --cores-root . run --setup --build --build-root build --target sim --tool verilator

help:
	@echo "----------------------------------------------------------------"
	@echo "Administrative Targets:"
	@echo "  clean          - removes all temporary files"
	@echo "  clean_libs     - removes the downloaded fusesoc libraries"
	@echo "  clean_build    - deletes the build"
	@echo "  clean_rlt      - deletes the simulation results"
	@echo "  help           - shows this menu"
	@echo
	@echo "FuseSoC Setup Targets"
	@echo "  setup          - install additional libraries"
	@echo "  update         - updates existing libraries"
	@echo
	@echo "Simulation Targets:"
	@echo "  sim_%          - verilates and simulates the "
	@echo "                   \"${For}:${PROJECT_NAME}:%\" design"
	@echo "  build_%        - verilates the"
	@echo "                   \"${For}:${PROJECT_NAME}:%\" design"
	@echo
	@echo "Analysis Targets"
	@echo "  svcoverage     - analyzes the coverage data generated by"
	@echo "                   verilator and outputs it to the sv_coverage"
	@echo "                   directory"
	@echo
	@echo "Helper Program Targets:"
	@echo
	@echo "Test Data Generation Targets:"
	@echo
	@echo "----------------------------------------------------------------"


# TARGET OVERRIDES





# GENERIC FUSESOC TARGETS

build_%: clean
	$(FUSESOC_BUILD_SIM) ${For}:${PROJECT_NAME}:$*

sim_%: build_%
	./build/sim-verilator/Vtb_$*



# COVERAGE TARGETS

svcoverage:
	cd build/sim-verilator && verilator_coverage logs/* --annotate coverage
	rm -rf sv_coverage
	mkdir sv_coverage
	cp build/sim-verilator/coverage/* sv_coverage



# HELPER PROGRAM COMPILATION TARGETS





# TEST DATA GENERATION TARGETS





# FUSESOC SETUP TARGETS

# fusesoc library setup commands look like this: fusesoc library add fusesoc_cores git@github.com:fusesoc/fusesoc-cores
# make sure to use the ssh method rather than the https method when loading from non-public git repos
setup:


reload:
	fusesoc library update



# CLEAN TARGETS

clean: clean_build clean_mt_test

clean_libs:
	rm -rf fusesoc_libraries
	rm fusesoc.conf

clean_build:
	rm -rf build

clean_rlt:
	rm -rf sv_coverage
	rm -f waveform.vcd
